transformations:
  - column: "total_bill"
    target_type: "float"
  - column: "sex"
    pre_type: "string"
    target_type: "int64"
    mapping:
      Male: 1
      Female: 0
  - column: "smoker"
    pre_type: "bool"
    target_type: "int64"
    mapping:
      Yes: 1
      No: 0
  - column: "day"
    pre_type: "string"
    target_type: "int64"
    mapping:
      Sun: 1
      Mon: 2
      Tue: 3
      Wed: 4
      Thur: 5 # Not Thu, it's Thur, it's due to the nature of the dataset
      Fri: 6
      Sat: 7
  - column: "time"
    pre_type: "string"
    target_type: "int64"
    mapping:
      Dinner: 1
      Lunch: 0
  - column: "size"
    target_type: "int64"
