"""Initial migration

Revision ID: 4a93c9835f1a
Revises: 
Create Date: 2025-02-15 22:20:45.802503

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4a93c9835f1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_registration',
                    sa.Column('file_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('file_id')
                    )
    op.create_table('data_issues',
                    sa.Column('file_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('row_missing', sa.Integer(), nullable=False),
                    sa.Column('rows_unknown_value', sa.Integer(), nullable=False),
                    sa.Column('rows_invalid_value', sa.Integer(), nullable=False),
                    sa.Column('rows_outlier', sa.Integer(), nullable=False),
                    sa.Column('features_missing', sa.Integer(), nullable=False),
                    sa.Column('label_missing', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['file_id'], ['file_registration.file_id'], ),
                    sa.PrimaryKeyConstraint('file_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_issues')
    op.drop_table('file_registration')
    # ### end Alembic commands ###
