"""Initial migration

Revision ID: 53446c711ef8
Revises: 
Create Date: 2025-02-18 11:14:32.018477

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53446c711ef8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_registration',
                    sa.Column('file_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('file_id')
                    )
    op.create_index(op.f('ix_file_registration_completed_at'), 'file_registration', ['completed_at'], unique=False)
    op.create_index(op.f('ix_file_registration_file_id'), 'file_registration', ['file_id'], unique=False)
    op.create_table('data_issues',
                    sa.Column('file_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
                    sa.Column('row_missing', sa.Integer(), nullable=False),
                    sa.Column('rows_unknown_value', sa.Integer(), nullable=False),
                    sa.Column('rows_invalid_value', sa.Integer(), nullable=False),
                    sa.Column('rows_outlier', sa.Integer(), nullable=False),
                    sa.Column('features_missing', sa.Integer(), nullable=False),
                    sa.Column('label_missing', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['file_id'], ['file_registration.file_id'], ),
                    sa.PrimaryKeyConstraint('file_id')
                    )
    op.create_index(op.f('ix_data_issues_file_id'), 'data_issues', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_issues_file_id'), table_name='data_issues')
    op.drop_table('data_issues')
    op.drop_index(op.f('ix_file_registration_file_id'), table_name='file_registration')
    op.drop_index(op.f('ix_file_registration_completed_at'), table_name='file_registration')
    op.drop_table('file_registration')
    # ### end Alembic commands ###
