"""add indices

Revision ID: ccb5826a61eb
Revises: 4a93c9835f1a
Create Date: 2025-02-15 23:05:54.387349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb5826a61eb'
down_revision: Union[str, None] = '4a93c9835f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_data_issues_file_id'), 'data_issues', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_registration_completed_at'), 'file_registration', ['completed_at'], unique=False)
    op.create_index(op.f('ix_file_registration_file_id'), 'file_registration', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_registration_file_id'), table_name='file_registration')
    op.drop_index(op.f('ix_file_registration_completed_at'), table_name='file_registration')
    op.drop_index(op.f('ix_data_issues_file_id'), table_name='data_issues')
    # ### end Alembic commands ###
