{
 "title": "Data Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "CSV parsing issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CSV parsing issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH file_cnt AS (\n    SELECT DATE(created_at) AS created_date,\n           COUNT(*) AS total_files,\n           SUM(CASE WHEN total_rows IS NULL THEN 1 ELSE 0 END) AS total_bad_csv\n    FROM data_issues\n    WHERE created_at >= $__timeFrom() \n    GROUP BY created_date\n)\nSELECT created_date,\n       f.total_files,\n       f.total_bad_csv,\n       ROUND((f.total_bad_csv * 100.0) / f.total_files, 2) AS bad_csv_percentage\nFROM file_cnt f\n"
    }
   ]
  },
  { "title": "Data issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Overall successful validation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT DATE(created_at) AS created_date,\n       ROUND(MAX(success_percent)::numeric, 2) AS max_success_percent,\n       ROUND(MIN(success_percent)::numeric, 2) AS min_success_percent,\n       ROUND(AVG(success_percent)::numeric, 2) AS avg_success_percent\nFROM data_issues\nWHERE total_rows IS NOT NULL\nAND created_at >= $__timeFrom() \nGROUP BY created_date"
    }
   ]
  },
  {
   "title": "Detailed failure modes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT DATE(created_at) AS created_date,\n       ROUND(AVG(missing_columns::numeric)::numeric, 2) AS avg_missing_columns,\n       ROUND(AVG(missing_values::numeric)::numeric, 2) AS avg_missing_values,\n       ROUND(AVG(unknon_numeric_values::numeric)::numeric, 2) AS avg_unknon_numeric,\n       ROUND(AVG(unknown_categorical_values::numeric)::numeric, 2) AS avg_unknown_categorical\nFROM data_issues\nWHERE total_rows IS NOT NULL\nAND created_at >= $__timeFrom()\nGROUP BY created_date\n"
    }
   ]
  }
 ]
}