{
 "title": "ML_engineering_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Statistics for label", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Predictions - Tip distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT tip\nFROM predictions \nWHERE predicted_at AT TIME ZONE 'Europe/Paris' >= $__timeFrom()"
    }
   ]
  },
  {
   "title": "Training - Tip distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT tip\nFROM training_data "
    }
   ]
  },
  { "title": "Statistics for features", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Predictions - Total bill distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT total_bill\nFROM predictions \nWHERE predicted_at AT TIME ZONE 'Europe/Paris' >= $__timeFrom() "
    }
   ]
  },
  {
   "title": "Training - Total bill distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT total_bill\nFROM training_data "
    }
   ]
  },
  {
   "title": "Predictions - Table size distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT size\nFROM predictions \nWHERE predicted_at AT TIME ZONE 'Europe/Paris' >= $__timeFrom() "
    }
   ]
  },
  {
   "title": "Training - Table size distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT size\nFROM training_data "
    }
   ]
  },
  {
   "title": "Gender distribution",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH training AS (\n  SELECT 100*SUM(CASE WHEN sex = 0 THEN 1 ELSE 0 END)/COUNT(*) AS female_percent,\n         100 - 100*SUM(CASE WHEN sex = 0 THEN 1 ELSE 0 END)/COUNT(*) AS male_percent\n  FROM training_data\n),\npred AS (\n  SELECT 100*SUM(CASE WHEN sex = 'Female' THEN 1 ELSE 0 END)/COUNT(*) AS female_percent,\n         100 - 100*SUM(CASE WHEN sex = 'Female' THEN 1 ELSE 0 END)/COUNT(*) AS male_percent\n  FROM predictions\n  WHERE predicted_at AT TIME ZONE 'Europe/Paris' >= $__timeFrom() \n)\nSELECT 'training' AS data, female_percent, male_percent\nFROM training\nUNION ALL\nSELECT 'predictions' AS data, female_percent, male_percent\nFROM pred"
    }
   ]
  },
  {
   "title": "Smoker distribution",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH training AS (\n  SELECT 100*SUM(CASE WHEN smoker = 0 THEN 1 ELSE 0 END)/COUNT(*) AS no_smoker_percent,\n         100 - 100*SUM(CASE WHEN smoker = 0 THEN 1 ELSE 0 END)/COUNT(*) AS smoker_percent\n  FROM training_data\n),\npred AS (\n  SELECT 100*SUM(CASE WHEN smoker = 'No' THEN 1 ELSE 0 END)/COUNT(*) AS no_smoker_percent,\n         100 - 100*SUM(CASE WHEN smoker = 'No' THEN 1 ELSE 0 END)/COUNT(*) AS smoker_percent\n  FROM predictions\n  WHERE predicted_at AT TIME ZONE 'Europe/Paris' >= $__timeFrom() \n)\nSELECT 'training' AS data, no_smoker_percent, smoker_percent\nFROM training\nUNION ALL\nSELECT 'predictions' AS data, no_smoker_percent, smoker_percent\nFROM pred"
    }
   ]
  },
  {
   "title": "Day distribution",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "WITH training AS (\n  SELECT 100*SUM(CASE WHEN day not in (1, 7) THEN 1 ELSE 0 END)/COUNT(*) AS weekday_percent,\n         100 - 100*SUM(CASE WHEN day not in (1, 7) THEN 1 ELSE 0 END)/COUNT(*) AS weekend_percent\n  FROM training_data\n),\npred AS (\n  SELECT 100*SUM(CASE WHEN day not in ('Sun', 'Sat') THEN 1 ELSE 0 END)/COUNT(*) AS weekday_percent,\n         100 - 100*SUM(CASE WHEN day not in ('Sun', 'Sat') THEN 1 ELSE 0 END)/COUNT(*) AS weekend_percent\n  FROM predictions\n  WHERE predicted_at AT TIME ZONE 'Europe/Paris' >= $__timeFrom() \n)\nSELECT 'training' AS data, weekday_percent, weekend_percent\nFROM training\nUNION ALL\nSELECT 'predictions' AS data, weekday_percent, weekend_percent\nFROM pred"
    }
   ]
  },
  {
   "title": "Meal time distribution",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "rawSql": "WITH training AS (\n  SELECT 100*SUM(CASE WHEN time = 0 THEN 1 ELSE 0 END)/COUNT(*) AS lunch_percent,\n         100 - 100*SUM(CASE WHEN time = 0 THEN 1 ELSE 0 END)/COUNT(*) AS dinner_percent\n  FROM training_data\n),\npred AS (\n  SELECT 100*SUM(CASE WHEN time = 'Lunch' THEN 1 ELSE 0 END)/COUNT(*) AS lunch_percent,\n         100 - 100*SUM(CASE WHEN time = 'Dinner' THEN 1 ELSE 0 END)/COUNT(*) AS dinner_percent\n  FROM predictions\n  WHERE predicted_at AT TIME ZONE 'Europe/Paris' >= $__timeFrom() \n)\nSELECT 'training' AS data, lunch_percent, dinner_percent\nFROM training\nUNION ALL\nSELECT 'predictions' AS data, lunch_percent, dinner_percent\nFROM pred"
    }
   ]
  }
 ]
}